// USER = Coming from client.
// MESSAGE = One person.
// BROADCAST = Everyone.

const emitterTypes = {
    SOCKET_CONNECT: 'connection',
    SOCKET_DISCONNECT: 'disconnect',
    SERVER_MESSAGE_USER_JOIN: 'SERVER_MESSAGE_USER_JOIN',
    SERVER_BROADCAST_ROOM_INFO: 'SERVER_BROADCAST_ROOM_INFO',
    SERVER_BROADCAST_USER_JOIN: 'SERVER_BROADCAST_USER_JOIN',
    SERVER_BROADCAST_USER_LEAVE: 'SERVER_BROADCAST_USER_LEAVE',
    SERVER_BROADCAST_USER_MESSAGE: 'SERVER_BROADCAST_USER_MESSAGE',
    USER_JOIN_ROOM: 'USER_JOIN_ROOM',
    USER_LEAVE_ROOM: 'USER_LEAVE_ROOM',
    USER_SEND_MESSAGE: 'USER_SEND_MESSAGE',
};

export default emitterTypes;